services:
  - type: web
    name: better-monopoly-server
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: dev
      - key: PORT
        value: 10000
      - key: APP_NAME
        value: Better-Monopoly-Server
      - key: API_PREFIX
        value: /api/v1
      - key: CORS_ORIGIN
        sync: false
      - key: LOG_LEVEL
        value: info
      - key: SWAGGER_ENABLED
        value: true
    autoDeploy: true
